name: Test Python Package

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install libsndfile1-dev sox libsox-dev
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Lint with flake8
      run: |
        pip install flake8 flake8-isort flake8-bugbear
        flake8 --disable-noqa

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

#   - uses: actions/create-release@v1
